# Generated by Django 5.1.3 on 2024-11-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_alter_state_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('short_description', models.TextField(blank=True, max_length=250, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('image_alt', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keyword', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='states.state')),
            ],
        ),
    ]
