# Generated by Django 5.1.3 on 2024-11-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_localities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localities',
            name='state',
        ),
        migrations.AddField(
            model_name='localities',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='states.cities'),
        ),
    ]
