# Generated by Django 5.0 on 2024-12-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0004_remove_localities_state_localities_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="cities",
            name="youtube_link",
            field=models.CharField(
                blank=True,
                default="https://www.youtube.com/@rdajaipur",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="contact_number",
            field=models.CharField(
                blank=True, default="8769422006", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="description",
            field=models.TextField(
                blank=True,
                default="Top Coaching for Sainik School, RMS, and RIMC Entrance Exams in Banswara Join the best coaching center in Banswara for Sainik School, Rashtriya Military School (RMS), and RIMC entrance exams. Achieve your dream of joining prestigious military schools with our expert guidance and proven success strategies.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="facebook_link",
            field=models.CharField(
                blank=True,
                default="https://www.facebook.com/Sainikschoolentranceexamcoaching/",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="image_alt",
            field=models.CharField(
                blank=True,
                default="Sainik School, RMS, and RIMC Entrance Exams in Banswara",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="instagram_link",
            field=models.CharField(
                blank=True,
                default="https://www.instagram.com/onlinesainikschoolcoaching/",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_description",
            field=models.CharField(
                blank=True,
                default="sainik school coaching, rashtriya military school coaching, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_keyword",
            field=models.TextField(
                blank=True,
                default="sainik school coaching, rashtriya military school coaching, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching, military school coaching in Banswara, rms coaching in Banswara, sainik school coaching in Banswara, rimc coaching in Banswara, military entrance exam preparation Banswara",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="Top Coaching for Sainik School, RMS, and RIMC Entrance Exams in Banswara",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="Expert coaching for Sainik School, Rashtriya Military School (RMS), and RIMC entrance exams in Banswara. Comprehensive preparation, experienced faculty, and proven results.",
                max_length=250,
                null=True,
            ),
        ),
    ]
