# Generated by Django 5.0 on 2025-01-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0007_cities_whatsapp_number_localities_whatsapp_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cities",
            name="latitude",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="cities",
            name="logitude",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="localities",
            name="latitude",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="localities",
            name="logitude",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="latitude",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="logitude",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
