# Generated by Django 5.0 on 2025-01-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0008_cities_latitude_cities_logitude_localities_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="pincode",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
