# Generated by Django 5.0 on 2025-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0009_state_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="cities",
            name="pincode",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
