# Generated by Django 5.0 on 2025-01-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0010_cities_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="short_description",
            field=models.TextField(
                blank=True, help_text="institute name", max_length=250, null=True
            ),
        ),
    ]
