# Generated by Django 5.0 on 2025-01-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0011_alter_state_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="localities",
            name="pincode",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
