# Generated by Django 5.0 on 2025-01-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0012_localities_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cities",
            name="description",
            field=models.TextField(
                blank=True,
                default="Top Coaching for Sainik School {loaction} , RMS, and RIMC Entrance Exams Join the best coaching center for Sainik School {loaction} , Rashtriya Military School (RMS), and RIMC entrance exams {loaction}. Achieve your dream of joining prestigious military schools with our expert guidance and proven success strategies {loaction}",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="image_alt",
            field=models.CharField(
                blank=True,
                default="Sainik School, RMS, and RIMC Entrance Exams",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_description",
            field=models.CharField(
                blank=True,
                default="sainik school coaching {loaction}, rashtriya military school coaching {loaction}, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching {loaction}",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_keyword",
            field=models.TextField(
                blank=True,
                default="sainik school coaching {loaction} , rashtriya military school coaching {loaction}, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching, military school coaching {loaction}, rms coaching, sainik school coaching, rimc coaching, military entrance exam preparation {loaction}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="Top Coaching for Sainik School {loaction}, RMS, and RIMC Entrance Exams {loaction}",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="Expert coaching for Sainik School {loaction}, Rashtriya Military School (RMS), and RIMC entrance exams {loaction}. Comprehensive preparation, experienced faculty, and proven results {loaction}",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="description",
            field=models.TextField(
                blank=True,
                default="Top Coaching for Sainik School {loaction} , RMS, and RIMC Entrance Exams Join the best coaching center for Sainik School {loaction} , Rashtriya Military School (RMS), and RIMC entrance exams {loaction}. Achieve your dream of joining prestigious military schools with our expert guidance and proven success strategies {loaction}.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="meta_description",
            field=models.CharField(
                blank=True,
                default="sainik school coaching {loaction}, rashtriya military school coaching {loaction}, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching {loaction}",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="meta_keyword",
            field=models.TextField(
                blank=True,
                default="sainik school coaching {loaction} , rashtriya military school coaching {loaction}, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching, military school coaching {loaction}, rms coaching, sainik school coaching, rimc coaching, military entrance exam preparation {loaction}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="Top Coaching for Sainik School {loaction}, RMS, and RIMC Entrance Exams {loaction}",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="Expert coaching for Sainik School {loaction}, Rashtriya Military School (RMS), and RIMC entrance exams {loaction}. Comprehensive preparation, experienced faculty, and proven results {loaction}.",
                max_length=250,
                null=True,
            ),
        ),
    ]
