# Generated by Django 5.0 on 2025-01-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0013_alter_cities_description_alter_cities_image_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cities",
            name="description",
            field=models.TextField(
                blank=True,
                default="Top Coaching for Sainik School location , RMS, and RIMC Entrance Exams Join the best coaching center for Sainik School location , Rashtriya Military School (RMS), and RIMC entrance exams location. Achieve your dream of joining prestigious military schools with our expert guidance and proven success strategies location",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_description",
            field=models.CharField(
                blank=True,
                default="sainik school coaching location, rashtriya military school coaching location, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching location",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_keyword",
            field=models.TextField(
                blank=True,
                default="sainik school coaching location , rashtriya military school coaching location, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching, military school coaching location, rms coaching, sainik school coaching, rimc coaching, military entrance exam preparation location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="Top Coaching for Sainik School location, RMS, and RIMC Entrance Exams location",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="Expert coaching for Sainik School location, Rashtriya Military School (RMS), and RIMC entrance exams location. Comprehensive preparation, experienced faculty, and proven results location",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="description",
            field=models.TextField(
                blank=True,
                default="Top Coaching for Sainik School location , RMS, and RIMC Entrance Exams Join the best coaching center for Sainik School location , Rashtriya Military School (RMS), and RIMC entrance exams location. Achieve your dream of joining prestigious military schools with our expert guidance and proven success strategies location.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="meta_description",
            field=models.CharField(
                blank=True,
                default="sainik school coaching location, rashtriya military school coaching location, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching location",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="meta_keyword",
            field=models.TextField(
                blank=True,
                default="sainik school coaching location , rashtriya military school coaching location, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching, military school coaching location, rms coaching, sainik school coaching, rimc coaching, military entrance exam preparation location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="Top Coaching for Sainik School location, RMS, and RIMC Entrance Exams location",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="Expert coaching for Sainik School location, Rashtriya Military School (RMS), and RIMC entrance exams location. Comprehensive preparation, experienced faculty, and proven results location.",
                max_length=250,
                null=True,
            ),
        ),
    ]
