# Generated by Django 5.0 on 2025-01-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0014_alter_cities_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cities",
            name="facebook_link",
            field=models.CharField(
                blank=True,
                default="https://www.facebook.com/Sainikschoolentranceexamcoaching/",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="image_alt",
            field=models.CharField(
                blank=True,
                default="Sainik School, RMS, and RIMC Entrance Exams",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="instagram_link",
            field=models.CharField(
                blank=True,
                default="https://www.instagram.com/onlinesainikschoolcoaching/",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="latitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cities",
            name="logitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_description",
            field=models.CharField(
                blank=True,
                default="sainik school coaching location, rashtriya military school coaching location, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="Top Coaching for Sainik School location, RMS, and RIMC Entrance Exams location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="pincode",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cities",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="Expert coaching for Sainik School location, Rashtriya Military School (RMS), and RIMC entrance exams location. Comprehensive preparation, experienced faculty, and proven results location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="facebook_link",
            field=models.CharField(
                blank=True,
                default="https://www.facebook.com/Sainikschoolentranceexamcoaching/",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="image_alt",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localities",
            name="instagram_link",
            field=models.CharField(
                blank=True,
                default="https://www.instagram.com/onlinesainikschoolcoaching/",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="latitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localities",
            name="logitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localities",
            name="meta_description",
            field=models.CharField(
                blank=True,
                default="sainik school coaching location, rashtriya military school coaching location, rms entrance exam coaching, rimc coaching, military school entrance exam coaching, sainik school entrance exam coaching, rashtriya military school entrance exam, rimc entrance exam coaching location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="Top Coaching for Sainik School location, RMS, and RIMC Entrance Exams location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localities",
            name="pincode",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localities",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="Expert coaching for Sainik School location, Rashtriya Military School (RMS), and RIMC entrance exams location. Comprehensive preparation, experienced faculty, and proven results location.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="latitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="logitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="pincode",
            field=models.CharField(blank=True, null=True),
        ),
    ]
