# myapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register('newss', NewssViewSet)
router.register('homePagenewss', NewsHomepageViewSet ,basename='News-homepage')
 




urlpatterns = [
    path('', include(router.urls)), # Include all the URLs generated by the router
]
