# Generated by Django 5.0 on 2024-12-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(blank=True, default="blog", max_length=255),
        ),
    ]
