# Generated by Django 5.0 on 2024-12-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0015_alter_blog_slug_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="slug_field",),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
