# Generated by Django 5.0 on 2024-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0016_remove_blog_slug_field_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
