# Generated by Django 5.0 on 2024-12-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0020_blogdata_remove_blog_slug"),
    ]

    operations = [
        migrations.DeleteModel(name="Blog",),
    ]
