# Generated by Django 5.0 on 2024-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0022_blog_delete_blogdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
