# Generated by Django 5.0 on 2024-12-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0023_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
