# Generated by Django 5.0 on 2024-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0025_rename_slug_blog_slug_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug_field",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
