# Generated by Django 5.0 on 2025-01-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0026_alter_blog_slug_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="meta_description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="meta_keywords",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="meta_title",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug_field",
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
