# myapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register('blogs', BlogsViewSet)
router.register('homePageBlogs', BlogHomepageViewSet ,basename='blog-homepage')



urlpatterns = [
    path('', include(router.urls)), # Include all the URLs generated by the router
]
