# myapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register('enquiry', EnquieryFormViewSet)
router.register('linescrollbar', LineScrollBarViewSet)
router.register('homepageimages',HomePageImagesViewSet)
router.register(r'topscrollers', HomepageTopScrollViewSet)
router.register(r'banners', HomepageViewSet)  # Register the ViewSet with the router
router.register('seo', SEOViewSet)
router.register(r'faqs', FAQListView)
router.register(r'homepagecontent', HomepageContentView)




urlpatterns = [
    path('', include(router.urls)), # Include all the URLs generated by the router
]
