# Generated by Django 4.2.16 on 2024-11-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                ("contact_number", models.CharField(max_length=100)),
                ("facebook_link", models.CharField(max_length=250)),
                ("instagram_link", models.CharField(max_length=250)),
                ("title", models.CharField(max_length=250)),
            ],
        ),
    ]
