# Generated by Django 4.2.16 on 2024-11-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="image_alt",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="meta_description",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="meta_keyword",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="meta_title",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="contact_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="facebook_link",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="instagram_link",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
