# Generated by Django 4.2.16 on 2024-11-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_alter_banner_meta_keyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopScroller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                ("image_alt", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("title", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="banner",
            name="contact_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="facebook_link",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image_alt",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="instagram_link",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="meta_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="meta_title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
