# Generated by Django 4.2.16 on 2024-11-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_topscroller_alter_banner_contact_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image", models.ImageField(blank=True, upload_to="covers/")),
                ("image_alt", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("meta_keyword", models.TextField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "facebook_link",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "instagram_link",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("title", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="topscroller", old_name="image", new_name="Image",
        ),
        migrations.AlterField(
            model_name="topscroller",
            name="title",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
