# Generated by Django 4.2.16 on 2024-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_homepageimages_rename_image_topscroller_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineScrollBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=500)),
            ],
        ),
    ]
