# Generated by Django 4.2.16 on 2024-11-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_linescrollbar"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnquiryForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=250)),
            ],
        ),
    ]
