# Generated by Django 5.1.3 on 2024-11-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_youtube_link'),
        ('homepage', '0007_enquiryform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryform',
            name='type',
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.course'),
        ),
    ]
