# Generated by Django 5.1.3 on 2024-11-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_enquiryform_type_enquiryform_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the page for SEO.', max_length=255)),
                ('description', models.TextField(help_text='The meta description of the page.')),
                ('keywords', models.CharField(help_text='Comma-separated keywords for SEO.', max_length=255)),
                ('canonical_url', models.URLField(help_text='Canonical URL to avoid duplicate content issues.')),
                ('og_title', models.CharField(help_text='Open Graph title.', max_length=255)),
                ('og_description', models.TextField(help_text='Open Graph description.')),
                ('og_image', models.URLField(help_text='URL of the Open Graph image.')),
                ('og_url', models.URLField(help_text='URL of the page for Open Graph.')),
                ('twitter_card', models.CharField(default='summary_large_image', help_text='Twitter card type.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
