# Generated by Django 5.0 on 2024-11-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_seo_og_image'),
        ('states', '0004_remove_localities_state_localities_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryform',
            name='cities',
            field=models.ManyToManyField(related_name='EnquiryForm', to='states.cities'),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='states',
            field=models.ManyToManyField(related_name='EnquiryForm', to='states.state'),
        ),
    ]
