# Generated by Django 5.0 on 2024-12-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_enquiryform_cities_enquiryform_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='homepagetitle',
            field=models.CharField(blank=True, help_text='The home Page Title of the page.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
