# Generated by Django 5.0 on 2024-12-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0012_seo_homepagetitle_seo_logo"),
    ]

    operations = [
        migrations.RemoveField(model_name="enquiryform", name="cities",),
        migrations.RemoveField(model_name="enquiryform", name="states",),
        migrations.AddField(
            model_name="enquiryform",
            name="cities",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="enquiryform",
            name="states",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
