# Generated by Django 5.0 on 2024-12-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0015_seo_location_seo_whatsapp_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seo",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
