# Generated by Django 5.0 on 2024-12-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0016_alter_seo_whatsapp_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="seo",
            name="scripts",
            field=models.TextField(
                blank=True,
                help_text="Custom scripts (e.g., tracking, analytics) to embed in the page.",
                null=True,
            ),
        ),
    ]
