# Generated by Django 5.0 on 2025-01-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0018_faq_alter_topscroller_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="faq", name="created_at",),
        migrations.RemoveField(model_name="faq", name="updated_at",),
    ]
