# Generated by Django 5.0 on 2025-01-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0019_remove_faq_created_at_remove_faq_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq", name="question", field=models.CharField(),
        ),
    ]
