# Generated by Django 5.0 on 2025-01-28 06:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0020_alter_faq_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
