# Generated by Django 5.0 on 2025-02-03 11:23

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0055_rename_image_multiple_images_imagess"),
        ("homepage", "0021_homepagecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="faq", name="answer", field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="faq", name="question", field=ckeditor.fields.RichTextField(),
        ),
    ]
