# Generated by Django 4.2.16 on 2024-11-12 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0002_alter_state_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('image_alt', models.CharField(blank=True, max_length=250, null=True)),
                ('course_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cities', models.ManyToManyField(related_name='courses', to='states.cities')),
                ('states', models.ManyToManyField(related_name='courses', to='states.state')),
            ],
        ),
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('image_alt', models.CharField(blank=True, max_length=250, null=True)),
                ('course_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_courses', to='courses.course')),
            ],
        ),
    ]
