# Generated by Django 4.2.16 on 2024-11-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='SubCoursecourse',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='sub_courses', to='courses.subcourse'),
            preserve_default='True',
        ),
    ]
