# Generated by Django 4.2.16 on 2024-11-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_subcourse_course_course_subcoursecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='SubCoursecourse',
        ),
        migrations.AddField(
            model_name='course',
            name='SubCoursecourse',
            field=models.ManyToManyField(blank='True', null='True', related_name='sub_courses', to='courses.subcourse'),
            preserve_default='True',
        ),
    ]
