# Generated by Django 5.1.3 on 2024-11-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_subcoursecourse_course_subcoursecourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='SubCoursecourse',
            new_name='SubCourses',
        ),
    ]
