# Generated by Django 5.1.3 on 2024-11-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_subcoursecourse_course_subcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='SubCourses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.subcourse'),
        ),
    ]
