# Generated by Django 5.1.3 on 2024-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcourse',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
