# Generated by Django 5.1.3 on 2024-11-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='slug_field',
        ),
    ]
