# Generated by Django 5.1.3 on 2024-11-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcourse',
            name='slug_field',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
