# Generated by Django 5.0 on 2024-11-27 03:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_subcourse_slug_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='SubCourses',
        ),
        migrations.AddField(
            model_name='subcourse',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='coursess', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='short_description',
            field=models.CharField(),
        ),
    ]
