# Generated by Django 5.0 on 2024-11-27 04:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_subcourses_subcourse_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
