# Generated by Django 5.0 on 2024-11-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcourse',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='coursessn', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcourse/'),
        ),
    ]
