# Generated by Django 5.0 on 2024-11-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_subcourse_courses_alter_subcourse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcourse',
            name='image',
        ),
        migrations.AddField(
            model_name='subcourse',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='short_description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
