# Generated by Django 5.0 on 2024-11-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_subcourse_image_subcourse_feature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcourse',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
