# Generated by Django 5.0 on 2024-11-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_feature_image_subcourse_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcourse',
        ),
        migrations.AddField(
            model_name='course',
            name='subcourses',
            field=models.ManyToManyField(blank=True, related_name='coursea', to='courses.subcourse'),
        ),
    ]
