# Generated by Django 5.0 on 2024-11-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_subcategory_subcourse_course_subcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcourses',
        ),
        migrations.AddField(
            model_name='course',
            name='SubCourse',
            field=models.ManyToManyField(blank=True, related_name='SubCourses', to='courses.subcourse'),
        ),
    ]
