# Generated by Django 5.0 on 2024-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_course_subcourse_remove_subcourse_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='meta_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='meta_keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
