# Generated by Django 5.0 on 2024-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_subcourse_description_alter_subcourse_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='SubcourseList',
            field=models.ManyToManyField(blank=True, null=True, related_name='SubcourseList', to='courses.subcourse'),
        ),
    ]
