# Generated by Django 5.0 on 2024-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_course_subcourselist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='SubcourseList',
        ),
        migrations.AddField(
            model_name='subcourse',
            name='courseList',
            field=models.ManyToManyField(blank=True, null=True, related_name='SubcourseList', to='courses.course'),
        ),
    ]
