# Generated by Django 5.0 on 2024-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_subcourse_courselist_course_subcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='SubCourses',
        ),
        migrations.AddField(
            model_name='subcourse',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='coursesn', to='courses.course'),
        ),
    ]
