# Generated by Django 5.0 on 2024-11-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_course_subcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcourses',
        ),
    ]
