# Generated by Django 5.0 on 2024-12-01 04:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_remove_course_subcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
