# Generated by Django 5.0 on 2024-12-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
