# Generated by Django 5.0 on 2024-12-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_subcourse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcourse',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='subcourses/'),
        ),
    ]
