# Generated by Django 5.0 on 2024-12-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_subcourse_courses_alter_subcourse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcourse',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='coursesn', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='covers/'),
        ),
    ]
