# Generated by Django 5.0 on 2024-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_subcourse_courses_alter_subcourse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
