# Generated by Django 5.0 on 2024-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_subcourse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcourse',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcourse',
            field=models.ManyToManyField(blank=True, null=True, related_name='subcategories', to='courses.subcourse'),
        ),
    ]
