# Generated by Django 5.0 on 2024-12-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0038_alter_course_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSeoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "og_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="og_images/"),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
