# Generated by Django 5.0 on 2024-12-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_courseseodata"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="short_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
