# Generated by Django 5.0 on 2024-12-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0042_alter_course_title_multiple_descriptions"),
    ]

    operations = [
        migrations.DeleteModel(name="multiple_descriptions",),
    ]
