# Generated by Django 5.0 on 2024-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0044_multiple_descriptions"),
        ("states", "0004_remove_localities_state_localities_city"),
    ]

    operations = [
        migrations.RemoveField(model_name="multiple_descriptions", name="title",),
        migrations.AlterField(
            model_name="course",
            name="localities",
            field=models.ManyToManyField(
                related_name="localities", to="states.localities"
            ),
        ),
    ]
