# Generated by Django 5.0 on 2024-12-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0045_remove_multiple_descriptions_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiple_descriptions",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
