# Generated by Django 5.0 on 2024-12-26 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0050_alter_course_meta_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiple_images",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multiple_image",
                to="courses.course",
            ),
        ),
    ]
