# Generated by Django 5.0 on 2024-12-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0053_rename_image_multiple_images_imagess"),
    ]

    operations = [
        migrations.RemoveField(model_name="multiple_images", name="imagess",),
        migrations.AddField(
            model_name="multiple_images",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="multiple_images",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
