# Generated by Django 5.0 on 2024-12-15 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsdata", "0001_initial"),
    ]
    operations = [
        migrations.RenameField(
            model_name="news", old_name="slug", new_name="slug_field",
        ),
    ]
