# Generated by Django 5.0 on 2025-01-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogsdata", "0002_rename_slug_blog_slug_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug_field",
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
