# myapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register('news', newsViewSet)
router.register('homePagenews', newsViewSet ,basename='news-homepage')

urlpatterns = [
    path('', include(router.urls)), # Include all the URLs generated by the router
]
